biantris/braintris

- src/assinatura-de-funcoes.md
> feat(ass-fun): add ass fn

- website/docusaurus.config.js
- website/src/components/HomepageFeatures.js
- website/src/css/custom.css
- website/src/pages/index.js
- website/src/pages/index.module.css
ref https://github.com/biantris/my-fullstack-journey/issues/36
> feat(home-page): improve home-page

- website/package.json
- website/yarn.lock
ref https://github.com/biantris/braintris/issues/40
> feat(nth): dump version nth

- docs/about.md
- docs/articles/_category_.json
- docs/articles/articles.md
- docs/articles/eventos-de-clique.md
- docs/javascript/_category_.json
- docs/javascript/javascript.md
- docusaurus.config.js
> feat(category): add category

- docs/about.md
fixes https://github.com/biantris/braintris/issues/97
> fix(about): fixes

- .gitignore
ref https://github.com/biantris/braintris/issues/159
> feat(remove): add yarn lock in git ignore

- docs/javascript/callback.md
- docusaurus.config.js
- src/pages/index.js
related https://github.com/biantris/braintris/issues/164
> fix(link): fix links

- docs/about.md
- docs/javascript/callback.md
ref https://github.com/biantris/braintris/issues/166
> fix(img): more fixes link to img

- docs/about.md
ref https://github.com/biantris/braintris/issues/158
> feat(work): up my current work

- docs/analyzes-perceptions.md
- docs/articles.md
- docs/front-end.md
- docs/issues.md
- docs/javascript/callback.md
- docs/javascript/eventos-de-clique.md
- docs/javascript/when-to-use-equal-two-points.md
- docs/life-hacks.md
- docs/recursividade.mdx
- docs/talks.md
related https://github.com/biantris/braintris/issues/41
> feat(tags): add tags in all pages

- docusaurus.config.js
ref https://github.com/biantris/braintris/issues/183
> feat(sponsor): add patreon button

- src/pages/index.js
ref https://github.com/biantris/braintris/issues/182
> feat(meta): improve metadata

- docusaurus.config.js
- package.json
- src/components/KnowledgeGraph/index.tsx
- yarn.lock
Fixes #31 
You can access your knowledge graph at `/braintris/en/knowledge-graph`
> feat: add graph first version

- docs/cs/_category_.json
- docs/cs/learn-computer-science.md
- docs/cs/sicp.md
related https://github.com/biantris/braintris/issues/186
> feat(cs): add content of cs

- docs/ledger.md
related https://github.com/biantris/braintris/issues/186
> feat(ledger): add ledger content

- docs/job/_category_.json
- docs/job/unitok/TIL.md
related https://github.com/biantris/braintris/issues/186
> feat(job): add til

- docs/mongoDB/_category_.json
- docs/mongoDB/query-optimization.md
> feat(query-op): add query optimization content

- docs/setup.md
ref https://github.com/biantris/braintris/issues/229
> feat(setup): add setup page

- docs/how-to-test.md
closes https://github.com/biantris/braintris/issues/230
> feat(test): add how to test note

- docusaurus.config.js
ref https://github.com/biantris/braintris/issues/294
> feat(vercel): test deploy on vercel

- docs/about.md
closes https://github.com/biantris/braintris/issues/356
> feat(improve-about): improve about

- docs/youtube.mdx
closes https://github.com/biantris/braintris/issues/359
> feat(youtube): add video

- docs/podcasts.mdx
closes https://github.com/biantris/braintris/issues/360
> feat(dev-amigo): add podcast episode

- docs/javascript/closures.md
ref https://github.com/biantris/braintris/issues/372
> feat(closures): add content about closures

- docusaurus.config.js
- package.json
- yarn.lock
closes https://github.com/biantris/braintris/issues/254
> feat(collapsible): add button to collapsible docsidebar

- docs/javascript/eventos-de-clique.md
- docs/math/_category_.json
- docs/math/media-ponderada.md
- docusaurus.config.js
- package.json
- src/css/custom.css
- yarn.lock
- closes https://github.com/biantris/braintris/issues/383
> feat(media-pond): add weight average content
